ALTER TABLE events ADD COLUMN seller_id BIGINT REFERENCES users(id);
ALTER TABLE events ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED';
ALTER TABLE events ADD COLUMN city VARCHAR(255);
ALTER TABLE events ADD COLUMN state VARCHAR(100);
ALTER TABLE events ADD COLUMN total_tickets INTEGER NOT NULL DEFAULT 100;
ALTER TABLE events ADD COLUMN sold_tickets INTEGER NOT NULL DEFAULT 0;
